name: Build openfec

on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 1'

jobs:

  build:
    strategy:
      matrix:
        image: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.image }}
    name: ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run cmake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Run make
        run: |
          cd build
          make -j2

      - name: Run tests
        run: |
          cd build
          make test

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: get-info
      run: |
        echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - id: debianise
      uses: twojstaryzdomu/debianise@HEAD
      with:
        create_changelog: true
        install_build_depends: false
        package: openfec
        debug: true

    - id: publish-release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ steps.debianise.outputs.files }}
        name: ${{ steps.get-info.outputs.GIT_TAG }}
        tag_name: ${{ steps.get-info.outputs.GIT_TAG }}
        fail_on_unmatched_files: true
        draft: true
        prerelease: true
